[env:samd21e18]
platform = atmelsam
board = sparkfun_qwiic_micro_samd21e
board_build.mcu = samd21e18a
board_build.f_cpu = 48000000L
framework = cmsis

build_flags =
    -I include
    -D__SAMD21E18A__
    -D__ATSAMD21E18A__

board_build.ldscript = linker.ld

; ST-LINK upload will be added after the project builds.
; The initial step is deliberately build-only.
